# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('subtitle', models.CharField(max_length=256, verbose_name='Subtitle')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('hitcount', models.IntegerField(verbose_name='HitCount')),
            ],
        ),
    ]
