# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_design_template', '0003_auto_20160908_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
