# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ex_design_template', '0004_auto_20160908_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
