# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
    ]
